# -*- coding: utf-8 -*-
"""Figure1_MotifsPlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qw-OcrOfbqXxzvRU6KTz2KAD7_L148f2

# T3 MOTIFS WITH Z-SCORE RANKING
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load data from CSV file
file_path = '/content/motifDiscovery_T3.csv'
data_T3 = pd.read_csv(file_path)

data_T3.head()

# Select only the 'ID' and 'Motif' columns
data_motifs_T3_fasta = data_T3[['Motif', 'Rank', 'P']]

# Show the resulting DataFrame
data_motifs_T3_fasta.head()

"""## VS APTEra2"""

!pip install biopython

from Bio.Seq import Seq

# Aptamer sequence you want to compare to
aptamer_sequence_T3_6 = Seq("TACTAGCCCTACCTGTACTCTCGAGCCGATTTTAAGGATC")  # Replace with your aptamer sequence

# List to store the results
matches = []

# Search for each motif in the aptamer sequence
for index, row in data_motifs_T3_fasta.iterrows():
    motif = Seq(row['Motif'])

    # Check if the motif is contained in the aptamer sequence
    if motif in aptamer_sequence_T3_6:
        matches.append((row['Rank'], row['Motif'], row['P']))

# Show results
if matches:
    print("Motifs found in the aptamer sequence:")
    for match in matches:
        print(f"Rank: {match[0]}, Motif: {match[1]}, P: {match[2]}")
else:
    print("No motifs were found in the aptamer sequence.")

"""###CSV"""

import pandas as pd

# Create a list of dictionaries with the provided data

motifs_T3_6 = [
    {"Rank": 1, "Motif": "TACTAG", "P": 0.00697},
    {"Rank": 4, "Motif": "ACTAG", "P": 0.01984},
    {"Rank": 17, "Motif": "TACTA", "P": 0.0576},
    {"Rank": 65, "Motif": "CTAGC", "P": 0.03127},
    {"Rank": 194, "Motif": "AGGATC", "P": 0.00232},
    {"Rank": 263, "Motif": "TAGCC", "P": 0.03135},
    {"Rank": 272, "Motif": "CCTACC", "P": 0.02588},
    {"Rank": 302, "Motif": "CTGTA", "P": 0.03524},
    {"Rank": 304, "Motif": "AGGAT", "P": 0.00746},
    {"Rank": 317, "Motif": "ACCTGT", "P": 0.01105},
    {"Rank": 318, "Motif": "CTACC", "P": 0.0816},
    {"Rank": 331, "Motif": "GCCCT", "P": 0.0494},
    {"Rank": 362, "Motif": "GTACTCT", "P": 0.00387},
    {"Rank": 375, "Motif": "ACCTG", "P": 0.03135},
    {"Rank": 405, "Motif": "AGCCCT", "P": 0.00982},
    {"Rank": 445, "Motif": "GGATC", "P": 0.01181},
    {"Rank": 483, "Motif": "CCTGT", "P": 0.05548},
    {"Rank": 568, "Motif": "CCTAC", "P": 0.0816},
    {"Rank": 603, "Motif": "GTACTC", "P": 0.01105},
    {"Rank": 640, "Motif": "AGCCC", "P": 0.02788},
    {"Rank": 647, "Motif": "TAAGGATC", "P": 0.00016},
    {"Rank": 649, "Motif": "GTACT", "P": 0.03524},
    {"Rank": 704, "Motif": "TAAGG", "P": 0.00746},
    {"Rank": 750, "Motif": "TGTACT", "P": 0.01242},
    {"Rank": 752, "Motif": "TACCT", "P": 0.09149},
    {"Rank": 754, "Motif": "AAGGATC", "P": 0.00045},
    {"Rank": 758, "Motif": "ACTCT", "P": 0.09207},
    {"Rank": 800, "Motif": "TAAGGA", "P": 0.00146},
    {"Rank": 801, "Motif": "AAGGAT", "P": 0.00146},
    {"Rank": 807, "Motif": "TACCTGT", "P": 0.00387},
    {"Rank": 820, "Motif": "TAAGGAT", "P": 0.00051},
    {"Rank": 828, "Motif": "TGTACTCT", "P": 0.00135},
    {"Rank": 846, "Motif": "AAGGA", "P": 0.00418},
    {"Rank": 852, "Motif": "TACCTGTAC", "P": 0.00023},
    {"Rank": 862, "Motif": "TGTAC", "P": 0.03524},
    {"Rank": 867, "Motif": "TACCTGTACT", "P": 8e-05},
    {"Rank": 881, "Motif": "TCGAGC", "P": 0.00368},
    {"Rank": 888, "Motif": "TCGAG", "P": 0.01181},
    {"Rank": 893, "Motif": "TACCTG", "P": 0.01105},
    {"Rank": 993, "Motif": "CGAGC", "P": 0.01049},
    {"Rank": 1051, "Motif": "TGTACTC", "P": 0.00387},
    {"Rank": 1054, "Motif": "TACCTGTA", "P": 0.00076},
    {"Rank": 1061, "Motif": "TCTCG", "P": 0.05548},
    {"Rank": 1064, "Motif": "CGAGCC", "P": 0.00327},
    {"Rank": 1144, "Motif": "TCTCGA", "P": 0.01105},
    {"Rank": 1224, "Motif": "TCGAGCC", "P": 0.00114}
]

# Convert the data to a DataFrame
df_T3_6 = pd.DataFrame(motifs_T3_6)

# Save the DataFrame to a CSV file
output_file = '/content/motifs_RankP_T3_6.csv'
df_T3_6.to_csv(output_file, index=False)

output_file

"""##VS APTEra3"""

from Bio.Seq import Seq

# Aptamer sequence you want to compare to
aptamer_sequence_T3_7 = Seq("TAGATCTCTGTTTGCCACTCTAGGCTGTTCTGCCAGGATC")  # Replace with your aptamer sequence

# List to store the results
matches = []

# Search for each motif in the aptamer sequence
for index, row in data_motifs_T3_fasta.iterrows():
    motif = Seq(row['Motif'])

    # Check if the motif is contained in the aptamer sequence
    if motif in aptamer_sequence_T3_7:
        matches.append((row['Rank'], row['Motif'], row['P']))

# Show results
if matches:
    print("Motifs found in the aptamer sequence:")
    for match in matches:
        print(f"Rank: {match[0]}, Motif: {match[1]}, P: {match[2]}")
else:
    print("No motifs were found in the aptamer sequence.")

"""### CSV"""

# Create a list of dictionaries with the provided data

motifs_T3_7 = [
    {"Rank": 3, "Motif": "TAGATC", "P": 0.00697},
    {"Rank": 7, "Motif": "AGATC", "P": 0.01984},
    {"Rank": 8, "Motif": "TAGAT", "P": 0.02228},
    {"Rank": 22, "Motif": "TCTAG", "P": 0.03524},
    {"Rank": 30, "Motif": "GATCTC", "P": 0.01105},
    {"Rank": 45, "Motif": "GCCAGGATC", "P": 3e-05},
    {"Rank": 61, "Motif": "GATCT", "P": 0.03524},
    {"Rank": 70, "Motif": "TCTGCCAGGA", "P": 1e-05},
    {"Rank": 75, "Motif": "GCCAGGAT", "P": 8e-05},
    {"Rank": 84, "Motif": "GCCAGGA", "P": 0.00024},
    {"Rank": 93, "Motif": "CCAGGATC", "P": 0.00022},
    {"Rank": 115, "Motif": "CAGGATC", "P": 0.00072},
    {"Rank": 116, "Motif": "CCAGGAT", "P": 0.00072},
    {"Rank": 127, "Motif": "TGCCA", "P": 0.03135},
    {"Rank": 132, "Motif": "CTGCCA", "P": 0.00982},
    {"Rank": 157, "Motif": "CTGCC", "P": 0.04921},
    {"Rank": 161, "Motif": "TCTGCCA", "P": 0.00344},
    {"Rank": 163, "Motif": "ATCTC", "P": 0.09207},
    {"Rank": 166, "Motif": "CCAGGA", "P": 0.00206},
    {"Rank": 173, "Motif": "CCACT", "P": 0.08212},
    {"Rank": 194, "Motif": "AGGATC", "P": 0.00232},
    {"Rank": 198, "Motif": "TCTGCCAGG", "P": 5e-05},
    {"Rank": 235, "Motif": "CAGGA", "P": 0.00663},
    {"Rank": 269, "Motif": "CTCTG", "P": 0.05548},
    {"Rank": 304, "Motif": "AGGAT", "P": 0.00746},
    {"Rank": 312, "Motif": "CAGGAT", "P": 0.00232},
    {"Rank": 326, "Motif": "TCTGCC", "P": 0.0175},
    {"Rank": 333, "Motif": "TTGCC", "P": 0.05548},
    {"Rank": 338, "Motif": "GCCAGG", "P": 0.00122},
    {"Rank": 397, "Motif": "CCAGG", "P": 0.0105},
    {"Rank": 423, "Motif": "TCTGCCAG", "P": 0.0004},
    {"Rank": 429, "Motif": "TCTGT", "P": 0.06202},
    {"Rank": 444, "Motif": "CTAGG", "P": 0.01181},
    {"Rank": 445, "Motif": "GGATC", "P": 0.01181},
    {"Rank": 447, "Motif": "ACTCTAG", "P": 0.00217},
    {"Rank": 452, "Motif": "GCCAC", "P": 0.02788},
    {"Rank": 458, "Motif": "CTCTAG", "P": 0.01105},
    {"Rank": 509, "Motif": "ACTCTA", "P": 0.01852},
    {"Rank": 540, "Motif": "TCTCTG", "P": 0.01969},
    {"Rank": 565, "Motif": "TTCTG", "P": 0.06229},
    {"Rank": 668, "Motif": "TCTGC", "P": 0.05548},
    {"Rank": 708, "Motif": "GCCAG", "P": 0.01048},
    {"Rank": 758, "Motif": "ACTCT", "P": 0.09207},
    {"Rank": 762, "Motif": "GTTCT", "P": 0.06229},
    {"Rank": 830, "Motif": "GTTCTG", "P": 0.00738},
    {"Rank": 831, "Motif": "CTGTTCTGCC", "P": 8e-05},
    {"Rank": 875, "Motif": "GTTTG", "P": 0.02354},
    {"Rank": 886, "Motif": "CTGTTC", "P": 0.01966},
    {"Rank": 889, "Motif": "CTGTTCTGC", "P": 0.00025},
    {"Rank": 894, "Motif": "TCTCT", "P": 0.14355},
    {"Rank": 977, "Motif": "GGCTGT", "P": 0.00246},
    {"Rank": 1008, "Motif": "GTTCTGCCA", "P": 0.00014},
    {"Rank": 1016, "Motif": "CTGTT", "P": 0.06229},
    {"Rank": 1020, "Motif": "GTTCTGCC", "P": 0.00071},
    {"Rank": 1022, "Motif": "GGCTG", "P": 0.00702},
    {"Rank": 1050, "Motif": "CTGTTCT", "P": 0.0069},
    {"Rank": 1082, "Motif": "CTGTTCTG", "P": 0.0008},
    {"Rank": 1142, "Motif": "CTCTA", "P": 0.09207},
    {"Rank": 1217, "Motif": "GTTCTGC", "P": 0.0023},
]

# Convert the data to a DataFrame
df_T3_7 = pd.DataFrame(motifs_T3_7)

# Save the DataFrame to a CSV file
output_file = '/content/motifs_RankP_T3_7.csv'
df_T3_7.to_csv(output_file, index=False)

output_file

"""# T4 MOTIFS WITH Z-SCORE RANKING

"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load data from CSV file
file_path = '/content/motifDiscovery_T4.csv'
data_T4 = pd.read_csv(file_path)

data_T4.head()

# Select only the 'ID' and 'Motif' columns
data_motifs_T4_fasta = data_T4[['Motif', 'Rank', 'P']]

# Show the resulting DataFrame
data_motifs_T4_fasta.head()

"""###VS APTEra4"""

import csv
from Bio.Seq import Seq

# Aptamer sequence you want to compare to
aptamer_sequence_T4_9 = Seq("TACTAGTCATGCCTGTCTATTCTTGTATTCTGCCATGATC") # Replace with your aptamer sequence

# List to store the results
matches = []

# Search for each motif in the aptamer sequence
for index, row in data_motifs_T4_fasta.iterrows():
    motif = Seq(row['Motif'])

    # Check if the motif is contained in the aptamer sequence
    if motif in aptamer_sequence_T4_9:
        matches.append((row['Rank'], row['Motif'], row['P']))

# Show results
if matches:
    print("Motifs found in the aptamer sequence:")
    for match in matches:
        print(f"Rank: {match[0]}, Motif: {match[1]}, P: {match[2]}")
else:
    print("No motifs were found in the aptamer sequence.")

# Save the results to a CSV file
csv_filename = "motifs_RankP_T4_9.csv"
with open(csv_filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Rank", "Motif", "P"])
    writer.writerows(matches)

print(f"Results saved in {csv_filename}")

"""## VS APTEra5"""

import csv
from Bio.Seq import Seq

# Aptamer sequence you want to compare to
aptamer_sequence_T4_10 = Seq("TACTAGTCCTACTGTCTGTGTAGAGCGTGCCGGAAGGATC")  # Replace with your aptamer sequence

# List to store the results
matches = []

# Search for each motif in the aptamer sequence
for index, row in data_motifs_T4_fasta.iterrows():
    motif = Seq(row['Motif'])

    # Check if the motif is contained in the aptamer sequence
    if motif in aptamer_sequence_T4_10:
        matches.append((row['Rank'], row['Motif'], row['P']))

# Show results
if matches:
    print("Motifs found in the aptamer sequence:")
    for match in matches:
        print(f"Rank: {match[0]}, Motif: {match[1]}, P: {match[2]}")
else:
    print("No motifs were found in the aptamer sequence.")

# Save the results to a CSV file
csv_filename = "motifs_RankP_T4_10.csv"
with open(csv_filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Rank", "Motif", "P"])
    writer.writerows(matches)

print(f"Results saved in {csv_filename}")